# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1510c1a26b1ce1fd774dacd56e980814355614a5601b283d67f24fc86fa03fd6f1d0e5b1cf81d912a3d7657866ad562dbb802158dfe42d00654c81a1972a81d8

test:
  secret_key_base: e38da90c4f3b40ff4c6b274bec492cf0b0575fff97509ecc5bdff201294b844df14288035ac2cfff8d39516c7c729015d97dd7bc8680b8dc42e5a45ce8fe1ffd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
